export const candlesData = [
    {
        id: 1,
        name: 'Midnight Garden',
        price: '33.00 $',
        status: 'OUT OF STOCK',
        img: '/assets/candles/candle.jpg',
    },
    {
        id: 2,
        name: 'Eucalyptus + Lavander',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-2.webp',
    },
    {
        id: 3,
        name: 'Meadowland',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-3.webp',
    },
    {
        id: 4,
        name: 'Geranium + Rose',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-4.webp',
    },
    {
        id: 5,
        name: 'Wanderlust',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-5.webp',
    },
    {
        id: 6,
        name: 'Forest Bathing',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-6.webp',
    },
    {
        id: 7,
        name: 'Moonglow',
        price: '24.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-7.jpg',
    },
    {
        id: 8,
        name: 'Cabin Retreat',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-8.png',
    },
    {
        id: 9,
        name: 'Cheer',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-9.png',
    },
    {
        id: 10,
        name: 'Grapefruit + Spearmint',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-10.jpg',
    },
    {
        id: 11,
        name: 'Orange + Clove',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-11.webp',
    },
    {
        id: 12,
        name: 'Autumn Woods',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-12.webp',
    },
    {
        id: 13,
        name: 'Vetiver + Smoke',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-13.webp',
    },
    {
        id: 14,
        name: 'Merry + Bright',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-14.png',
    },
    {
        id: 15,
        name: 'Hello Sunshine',
        price: '33.00 $',
        status: 'IN STOCK',
        img: '/assets/candles/candle-15.png',
    },
];
